spring:
  application:
    name: demo

   #Mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.50:3310/hrpro?characterEncoding=utf-8
    username: root
    password: dockerTest

  #Redis
  redis:
    database: 0
    host: 192.168.10.50
    port: 6390
    password: rockerRedis
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 18000
        min-idle: 0
    #日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

  #mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #sql日志
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag





